env:
  matrix:  
    - DOCKERFILE=docker/Dockerfile.bionic
      PYTHON=python3
    - DOCKERFILE=docker/Dockerfile.arch
      PYTHON=python

sudo: required

language: generic

services:
  - docker

install:
  - |
    docker build -f ${DOCKERFILE} --pull --tag linuxwhatelse/dups .

script:
  - |
    docker run --rm -it -v $(pwd):/dups linuxwhatelse/dups \
      bash -c "/usr/bin/ssh-keygen -A && /usr/sbin/sshd && \
        ${PYTHON} -m unittest discover -v -s /dups/tests"

