env:
  matrix:
    - DIST=archlinux
      PYTHON=python
      PKG_DIR=data/pkg/archlinux/

    - DIST=bionic
      PYTHON=python3
      PKG_DIR=data/pkg/debian/

    - DIST=stretch
      PYTHON=python3
      PKG_DIR=data/pkg/debian/

sudo: required
language: generic

services:
  - docker

install:
  - |
    docker build -f data/docker/Dockerfile.${DIST} \
      --pull --tag linuxwhatelse/dups-${DIST} .

script:
  - |
    docker run --rm -it -v $(pwd):/dups:ro linuxwhatelse/dups-${DIST} \
      /dups/data/scripts/travis/test-install.sh ${PKG_DIR}

  - |
    docker run --rm -it -v $(pwd):/dups:ro linuxwhatelse/dups-${DIST} \
      /dups/data/scripts/travis/test-dups.sh ${PYTHON}
