env:
  matrix:
    - DIST=arch
      DOCKERFILE=data/docker/Dockerfile.arch
      PYTHON=python
      PIP=pip

    - DIST=bionic
      DOCKERFILE=data/docker/Dockerfile.bionic
      PYTHON=python3
      PIP=pip3
      BUILD_SCRIPT=/dups/data/pkg/debian/build.sh

    - DIST=stretch
      DOCKERFILE=data/docker/Dockerfile.stretch
      PYTHON=python3
      PIP=pip3
      BUILD_SCRIPT=/dups/data/pkg/debian/build.sh

sudo: required
language: generic

services:
  - docker

install:
  - docker build -f ${DOCKERFILE} --pull --tag linuxwhatelse/dups-${DIST} .

script:
  - |
    docker run --rm -it -v $(pwd):/dups linuxwhatelse/dups-${DIST} bash -c \
      "${PIP} install /dups && dups --help"

  - |
    docker run --rm -it -v $(pwd):/dups linuxwhatelse/dups-${DIST} bash -c \
      "/usr/sbin/sshd && ${PYTHON} -m unittest discover -v -s /dups/tests"

after_success:
  - |
    if [ ! -z ${BUILD_SCRIPT} ]; then
      docker run --rm -it -v $(pwd):/dups linuxwhatelse/dups-${DIST} \
        ${BUILD_SCRIPT}
    fi
